## server config
server:
  port: 8080

## driver config
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/officedb
    username: officenotfound
    password: officenotfound
  web:
    resources:
      static-locations: classpath:/static/
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
      location: upload-dir
      enabled: true
## mybatis config
mybatis:
  mapper-locations: mapper/**/*.xml
  configuration:
    map-underscore-to-camel-case: true
  type-aliases-package: com.office.notfound


#logging:
#  level:
#    # 스프링 시큐리티 로깅 레벨
#    org.springframework.security: info
#    # 프로젝트 로깅 레벨
#    com.ohgiraffers.semi: debug
#    # 마이바티스 로깅 레벨
#    org.mybatis: info

# 이미지 업로드를 위한 사용자 정의 변수 설정 (@Value 어노테이션 복습)
image:
  add-resource-locations: classpath:/static/
  add-resource-handler: /**
  image-dir: build/resources/main/static/img/store
  image-url: /img/store

portone:
  api-key: 8266201362865180
  api-secret: CO2ouD8rGkcOcUc99QTznben0b7fKBJAuJAIvoLUv8OkW0Yz0284Wg8bLnaDdBMLzSNKfju3JI2K05lF